name: Build PDF

on:
  push:
    paths:
      - "main.typ"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate README from Typst
        run: python convert.py main.typ README.md

      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz | tar xJ
          sudo mv typst-*/typst /usr/local/bin/

      - name: Build PDF
        run: typst compile main.typ main.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-pdf
          path: main.pdf
